### ISSUE TITLE
Problem while trying to install stackrox by using ArgoCD -  waiting for completion of hook /PersistentVolumeClaim/central-db

### ISSUE THREAD

**Issue by Woj-Teh** [stackrox/stackrox#11957]
Hello Team.
Cluster: AKS 1.28
Helm Chart: 4.4.4 (the newest)
I would like to install stackrox on an AKS cluster using argoCd. Unfortunately, when I try to install it, I get an error regarding PVC. I saw that someone had a similar error and the response was that he needed to add a customize section in HELM I did that too, but it didn't help either. PVC was created and now is in pending status (see attachemnet) waitng for the first consumer - so I believe it is proper behaviour. Manual instalaltion works, problem is only while I try to install it using ArgoCD. . I paste the Argo Application below.
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stackrox-central-services
  namespace: argocd
spec:
  project: test
  source:
    repoURL: 'https://charts.stackrox.io'
    targetRevision: "400.4.4"
    chart: stackrox-central-services
    helm:
      values: |
        scanner:
          disable: true
        central:
          persistence:
            none: true
        system:
          enablePodSecurityPolicies: false
        customize:
          other:
            persistentvolumeclaim/central-db:
              annotations:
                helm.sh/hook: null
                helm.sh/hook-delete-policy: null
                helm.sh/resource-policy: null
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: stackrox
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
    automated:
      prune: true
      selfHeal: true
 
```

![image](https://github.com/user-attachments/assets/e63d7fa9-921b-44be-aafc-6f0419ef6d17)

![image](https://github.com/user-attachments/assets/bcc7aaca-553d-4945-a1b3-2b21fc16e7ba)

Wojtek
