### ISSUE TITLE
Unable to Upgrade Stackrox

### ISSUE THREAD

**Issue by jseiser** [stackrox/stackrox#12056]
This happens with every release.  We are to the point where we are going to need to remove stackrox and go back to kubeclarity.  I wanted to post here to see if there is anything we can do before we spend the time reverting.

Process

1. We Install Helm Charts with Terraform.
2. We generated the `stackrox-init-bundle.yaml` out of band since stackrox doesnt support using cert-manager
3. We pull down the values from `stackrox-init-bundle.yaml` and pass them in as inputs to `secured-cluster-services`

This works, stackrox is up and running.

1. We bump Chart versions
2. `secured-cluster-services` will error out every time with the follow

```
│ Error: malformed chart or values: 
│ 	templates/: template: stackrox-secured-cluster-services/templates/upgrader-serviceaccount.yaml:1:4: executing "stackrox-secured-cluster-services/templates/upgrader-serviceaccount.yaml" at <include "srox.init" .>: error calling include: template: stackrox-secured-cluster-services/templates/_init.tpl:114:3: executing "srox.init" at <include "srox.getStorageClasses" (list $)>: error calling include: template: stackrox-secured-cluster-services/templates/_storage_classes.tpl:20:12: executing "srox.getStorageClasses" at <include "srox.safeLookup" (list $ $lookupResult "storage.k8s.io/v1" "StorageClass" "" "")>: error calling include: template: stackrox-secured-cluster-services/templates/_lookup.tpl:18:7: executing "srox.safeLookup" at <include "srox._doLookup" (list $ $testOut "v1" "ServiceAccount" $._rox._namespace "default")>: error calling include: template: stackrox-secured-cluster-services/templates/_lookup.tpl:39:9: executing "srox._doLookup" at <tpl "{{ $_ := set .out \"result\" (lookup .apiVersion .kind .ns .name) }}" $tplArgs>: error calling tpl: error during tpl function execution for "{{ $_ := set .out \"result\" (lookup .apiVersion .kind .ns .name) }}": template: stackrox-secured-cluster-services/templates/upgrader-serviceaccount.yaml:1:53: executing "stackrox-secured-cluster-services/templates/upgrader-serviceaccount.yaml" at <.ns>: wrong type for value; expected string; got interface {}
│ 
│   with helm_release.stackrox-secured-cluster-services,
│   on main.tf line 66, in resource "helm_release" "stackrox-secured-cluster-services":
│   66: resource "helm_release" "stackrox-secured-cluster-services" {
│ 
╵
```
3. We have to uninstall and re-install everything and it works again.  

The values file itself, with TF templating. Note, 90% of the values is just removing SeLinux ( doesnt work on bottle rocket) and removing the node affinities ( do not work in EKS )

```
meta:
  namespaceOverride: stackrox

clusterName: ${cluster_name}

scanner:
  disable: true

scannerV4:
  disable: false
  indexer:
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution: []
  matcher:
      affinity:
          nodeAffinity:
              preferredDuringSchedulingIgnoredDuringExecution: []
  db:
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution: []

ca:
  cert: |
      ${indent(6,ca_cert)}
sensor:
  serviceTLS:
    cert: |
        ${indent(8,sensor_cert)}
    key: |
        ${indent(8,sensor_key)}
  affinity:
     nodeAffinity:
       preferredDuringSchedulingIgnoredDuringExecution: []
admissionControl:
  serviceTLS:
    cert: |
        ${indent(8,admissioncontrol_cert)}
    key: |
        ${indent(8,admissioncontrol_key)}
  affinity:
     nodeAffinity:
       preferredDuringSchedulingIgnoredDuringExecution: []
collector:
  serviceTLS:
    cert: |
        ${indent(8,collector_cert)}
    key: |
        ${indent(8,collector_key)}
  disableSELinuxOptions: true
```

**Comment by mclasmeier** [comment]
Hello @jseiser,
To follow-up on this issue:

From the rendering error message it seems that something is wrong with the propagation of `namespace` required for the lookup of Kubernetes resources on the cluster.

What I have tried as a first stab at investigating this issuse is the following:

I have basically taken your `values.yaml` and just did minor changes to remove the terraforming code:

```
meta:
  namespaceOverride: stackrox

clusterName: foo

scanner:
  disable: true

scannerV4:
  disable: false
  indexer:
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution: []
  matcher:
      affinity:
          nodeAffinity:
              preferredDuringSchedulingIgnoredDuringExecution: []
  db:
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution: []

ca:
  cert: |
      XXX
sensor:
  serviceTLS:
    cert: |
        XXX
    key: |
        XXX
  affinity:
     nodeAffinity:
       preferredDuringSchedulingIgnoredDuringExecution: []
admissionControl:
  serviceTLS:
    cert: |
        XXX
    key: |
        XXX
  affinity:
     nodeAffinity:
       preferredDuringSchedulingIgnoredDuringExecution: []
collector:
  serviceTLS:
    cert: |
        XXX
    key: |
        XXX
  disableSELinuxOptions: true
```

I have then tried to render the chart (v4.5.0) using the following command:

```
$ helm template stackrox-secured-cluster-services ~/go/src/github.com/stackrox/helm-charts/4.5.0/secured-cluster-services -f values.yaml 
```

Rendering succeeded without error. So I am not sure what is happening here. Could you check if this also works for you?

Thanks.
