### ISSUE TITLE
roxctl used in tekton image tasks aren't executable as script

### ISSUE THREAD

**Issue by shin-san** [stackrox/stackrox#5053]
### Bug report
The [rhacs-image-scan Tekton Task](https://hub.tekton.dev/tekton/task/rhacs-image-scan)'s image would throw an error when `script` is used as opposed to `args` as per details below.

Since all rhacs-related Tekton Tasks are using the same `roxctl` image, it is fair to say that the following Tekton Tasks are all affected:
1. `rhacs-image-scan`
2. `rhacs-image-check`
3. `rhacs-deployment-check`

```
    - name: rox-image-scan
      script: >-
        #!/usr/bin/env sh

        set -ex

        echo "Initiating image scan..."

        roxctl image scan --endpoint=$(ROX_CENTRAL_ENDPOINT)
        --insecure-skip-tls-verify=$(INSECURE) --output=$(OUTPUT)
        --image=$(IMAGE) >> /tmp/image-scan-report

        cat /tmp/image-scan-report | tee $(results.image-scan-report.path)
```
```
image-scan
STEP-ROX-IMAGE-SCAN

2023/03/01 00:54:25 Error executing command: fork/exec /tekton/scripts/script-0-9wm4x: no such file or directory
```
### Expected behavior
Able to use `script` in a Tekton Task

### Steps to reproduce the problem
Execute the following Task using `roxctl` image:
```
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: rhacs-image-scan
  annotations:
    description: >-
      Scan an image with Red Hat Advanced Cluster Security.
spec:
  results:
    - name: image-scan-report
      description: Image Scan Report
  steps:
    - name: print-version
      image: "quay.io/stackrox-io/roxctl:3.71.0"
      script: |-
        #!/usr/bin/env sh
        set -ex
        
        echo "Initiating image scan..."
        roxctl version
```

**Comment by ovalenti** [comment]
Hello @shin-san, and thanks for this report.

When you run the task, do you get the output of the "echo" commands before it fails ? This is just to check whether the script runs at all.

**Comment by shin-san** [comment]
Hi @ovalenti, unfortunately it does not even get to run the `echo` command. It seems that tekton was unable to execute `shell` command from what I have tested.

**Comment by ovalenti** [comment]
It would be strange, but could it be that `/usr/bin/env` or the shell does not exist in the image, @shin-san ?

**Comment by shin-san** [comment]
I tested `script` without `/usr/bin/env` or `/bin/bash`, and based from the outcome, `script` defaults to using shell to execute the commands you provide it and that itself is an issue if the image does not contain shell as part of its containerisation.

```
  steps:
    - image: quay.io/stackrox-io/roxctl:3.74.0
      name: rox-image-scan
      script: roxtctl version
```

Outcome:
```
STEP-ROX-IMAGE-SCAN

2023/03/01 21:31:48 Error executing command: fork/exec /tekton/scripts/script-0-v9rlc: no such file or directory
```
