### ISSUE TITLE
Helm chart sync fails via ArgoCD caused by helm pre-install hooks on PVCs

### ISSUE THREAD

**Issue by dan1el-k** [stackrox/stackrox#5191]
# Issue description
When trying to deploy the OSS Stackrox helmcharts (https://github.com/stackrox/helm-charts/tree/main/opensource) via a GitOps tool like ArgoCD, the deployment never succeeds.

# Details
ArgoCD maps the Helm hooks to ArgoCD hooks.
ArgoCD has an default opinion(can be customized though) when a resources is seen "Healthy".

In case of a PVC, the resources is "Healthy" once it is in status "bound" (see https://argo-cd.readthedocs.io/en/stable/operator-manual/health/#persistentvolumeclaim)

As the charts delivers all PV & PVCs with a Helm hook "pre-install", those objects gets synced first, before any deployment. This causes a situation, that ArgoCD is not continuing syncing other elements without the same "pre-install" hook, which is the case for the deployment objects. 
The PVC however just reaches state "bound" once the deployment would have been deployed.
**-> We are ending up in a DeadLock and ArgoCD stays in "Syncing" phase forever.**

```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $claimName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "srox.labels" (list . "persistentvolumeclaim" "central-db") | nindent 4 }}
  annotations:
    {{- include "srox.annotations" (list . "persistentvolumeclaim" "central-db") | nindent 4 }}
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/resource-policy": keep
    "helm.sh/hook-delete-policy": never
```

# Workaround

The only way I found at the moment, is to manually modify the upstream chart, and comment the Helm hooks `"helm.sh/hook": "pre-install,pre-upgrade"` of PV and PVCs following 2 files:

- 01-central-11-db-pvc.yaml
- 01-central-11-pvc.yaml

e.g.
```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $claimName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "srox.labels" (list . "persistentvolumeclaim" "central-db") | nindent 4 }}
  annotations:
    #"helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/resource-policy": keep
    "helm.sh/hook-delete-policy": never
```

# Proposed fix

Remove the `helm.sh/hook": "pre-install,pre-upgrade` from files:

- 01-central-11-db-pvc.yaml
- 01-central-11-pvc.yaml

or move them fully to the values.yaml as default, as the end-user could then override them to their needs.
