### ISSUE TITLE
External postgress connection string is created incorrectly

### ISSUE THREAD

**Issue by DarthSlider** [stackrox/stackrox#5374]
### Issue description
Postgress connection string generation is incorrect

### Details
Here is my helm values:
```
  db:
    enabled: true
    external: true
    source:
      connectionString: postgresql://user@10.0.0.1:5000/stackrox-db
      minConns: 10
      maxConns: 90
      statementTimeoutMs: 60000
    password:
      value: <path:dp-srv/prod/patroni/prod1#stackrox-prod>
  ```
Here is an error i`ve got:
```   
globaldb: 2023/03/23 22:42:59.846963 postgres.go:84: Fatal: Could not parse postgres config: Could not parse postgres config: cannot parse `postgresql:xxxxxx@10.48.5.69:5000/stackrox-db-prod statement_timeout=60000 pool_min_conns=10 pool_max_conns=90 password=xxxxx`: failed to parse as URL (parse "postgresql://stackrox-prod@10.48.5.69:5000/stackrox-db-prod statement_timeout=60000 pool_min_conns=10 pool_max_conns=90 password=Non-Masked-Password\n": net/url: invalid control character in URL)
```
Looks like there are 2 erorrs, one in helm chart:
https://github.com/stackrox/helm-charts/blob/main/3.74.1/central-services/templates/01-central-08-external-db-configmap.yaml#L16
It should be 
```
source: {{ ._rox.central.db.source.connectionString }}?statement_timeout={{ ._rox.central.db.source.statementTimeoutMs }}&pool_min_conns={{ ._rox.central.db.source.minConns }}&pool_max_conns={{ ._rox.central.db.source.maxConns }}
```
instead

And another one is here:
https://github.com/stackrox/stackrox/blob/d3911f6e206aa05093b3c9b6d878426231587723/pkg/postgres/pgconfig/config.go#L36
I`m not that good with golang, but looks like it should be:
```
source := fmt.Sprintf("%s&password=%s", centralConfig.CentralDB.Source, password)
```

But it would be even better to add password to the username separated with ":", because then it is added as an parameter it is not masked properly in logs.
